[book]
authors = []
language = "zh"
src = "."
title = "AI 日刊 - By 张褚"
create-missing = true  

[output.html]
git-repository-url = "https://github.com/amjack/CloudFlare-AI-Insight-Daily"
default-theme = "light"
preferred-dark-theme = "navy"
